#!/bin/sh

# Post-installation shell script for Debian package

BINDIR=/usr/local/syna/bin
SCRIPT=$BINDIR/streamer_router.sh

sudo chmod 755 $SCRIPT
sudo chown root:root $SCRIPT

SYSTEMD=/etc/systemd/system
SERVICE=pinormos-streamer-router.service

# Start and enable service
sudo ln -sf /lib/systemd/system/$SERVICE $SYSTEMD/$SERVICE
sudo systemctl daemon-reload
sudo systemctl start $SERVICE
sudo systemctl enable $SERVICE
